### PR TITLE
 ability to add classes to the table itself

### PR DESCRIPTION
**Pull request by hougasian**

### CODE REVIEW

**Comment by hougasian** [comment]
@gionkunz does this seem helpful?

**Comment by gionkunz** [comment]
Hey there! Yes, that sounds reasonable. Can you please only comit the source files? Once merged Ill bump the version, create the dist files and publish to npm / git tag

**Comment by hougasian** [comment]
@gionkunz `dist/` files removed. Thanks!

**Comment by gionkunz** [comment]
I've published 0.0.5 on npm

**Comment by hougasian** [comment]
👍

**Pull request merged**
